/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import command.Invoker;
import controller.DatabaseController;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.SQLException;
import model.ResultSetTableModel;
import javax.sql.rowset.CachedRowSet;

/**
 *
 * @author Sth0r
 */
public class GUI extends javax.swing.JFrame {

    private Invoker invoker;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDialog = new javax.swing.JDialog();
        addDialogIDLabel1 = new javax.swing.JLabel();
        addDialogIDField1 = new javax.swing.JTextField();
        addDialogFirstnameField1 = new javax.swing.JTextField();
        addDialogNameLabel1 = new javax.swing.JLabel();
        addDialogLastnameLabel1 = new javax.swing.JLabel();
        addDialogLastnameField1 = new javax.swing.JTextField();
        addDialogBalance = new javax.swing.JLabel();
        addDialogBalanceField1 = new javax.swing.JTextField();
        addDialogCreditLimitField1 = new javax.swing.JTextField();
        addDialogCreditLimit = new javax.swing.JLabel();
        addDialogEmailLabel = new javax.swing.JLabel();
        CItabEmailField1 = new javax.swing.JTextField();
        addDialogPhoneField1 = new javax.swing.JTextField();
        addDialogObsLabel = new javax.swing.JLabel();
        addDialogPhoneLabel = new javax.swing.JLabel();
        addDialogDiscartButton = new javax.swing.JButton();
        addDialogAcceptButton = new javax.swing.JButton();
        Customer_info_tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        CItab_add_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CItab_edit_button = new javax.swing.JButton();
        CItab_delete_button = new javax.swing.JButton();
        CItab_Push_button = new javax.swing.JButton();
        CItab_fetch_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        addDialogIDLabel1.setText("ID:");

        addDialogIDField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDialogIDField1ActionPerformed(evt);
            }
        });

        addDialogFirstnameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDialogFirstnameField1ActionPerformed(evt);
            }
        });

        addDialogNameLabel1.setText("First name:");

        addDialogLastnameLabel1.setText("Last name:");

        addDialogBalance.setText("Balance:");

        addDialogCreditLimitField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDialogCreditLimitField1ActionPerformed(evt);
            }
        });

        addDialogCreditLimit.setText("Credit limit:");

        addDialogEmailLabel.setText("Email:");

        CItabEmailField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CItabEmailField1ActionPerformed(evt);
            }
        });

        addDialogObsLabel.setText("OBS eg \"-200\"");

        addDialogPhoneLabel.setText("Phone:");

        addDialogDiscartButton.setText("Discart");
        addDialogDiscartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDialogDiscartButtonActionPerformed(evt);
            }
        });

        addDialogAcceptButton.setText("Accept");
        addDialogAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDialogAcceptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addDialogNameLabel1)
                    .addComponent(addDialogIDLabel1)
                    .addComponent(addDialogLastnameLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDialogLayout.createSequentialGroup()
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addDialogLastnameField1)
                            .addComponent(addDialogIDField1)
                            .addComponent(addDialogFirstnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addDialogEmailLabel)
                            .addComponent(addDialogCreditLimit)
                            .addComponent(addDialogBalance)))
                    .addComponent(addDialogDiscartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDialogLayout.createSequentialGroup()
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addDialogCreditLimitField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addDialogBalanceField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CItabEmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addDialogLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(addDialogPhoneLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addDialogPhoneField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addDialogLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addDialogObsLabel))))
                    .addComponent(addDialogAcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDialogIDField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDialogIDLabel1)
                    .addComponent(addDialogEmailLabel)
                    .addComponent(CItabEmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDialogPhoneField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDialogPhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDialogNameLabel1)
                    .addComponent(addDialogFirstnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDialogCreditLimit)
                    .addComponent(addDialogCreditLimitField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDialogLastnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDialogBalanceField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDialogObsLabel)
                    .addComponent(addDialogLastnameLabel1)
                    .addComponent(addDialogBalance))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDialogAcceptButton)
                    .addComponent(addDialogDiscartButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CItab_add_button.setText("Add");
        CItab_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CItab_add_buttonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First name", "Last name", "balance", "Credit limit", "Email", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("ID");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("First name");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Last name");
        jTable1.getColumnModel().getColumn(3).setHeaderValue("balance");
        jTable1.getColumnModel().getColumn(4).setHeaderValue("Credit limit");
        jTable1.getColumnModel().getColumn(5).setHeaderValue("Email");
        jTable1.getColumnModel().getColumn(6).setHeaderValue("Phone");

        jScrollPane2.setViewportView(jScrollPane1);

        CItab_edit_button.setText("Edit");
        CItab_edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CItab_edit_buttonActionPerformed(evt);
            }
        });

        CItab_delete_button.setText("Delete");
        CItab_delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CItab_delete_buttonActionPerformed(evt);
            }
        });

        CItab_Push_button.setText("Push");

        CItab_fetch_button.setText("Fetch");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CItab_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CItab_edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CItab_delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CItab_fetch_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CItab_Push_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CItab_add_button)
                    .addComponent(CItab_edit_button)
                    .addComponent(CItab_delete_button)
                    .addComponent(CItab_fetch_button)
                    .addComponent(CItab_Push_button))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Customer_info_tab.addTab("Customer info", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        Customer_info_tab.addTab("Event log", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Customer_info_tab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Customer_info_tab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CItab_delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CItab_delete_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CItab_delete_buttonActionPerformed

    private void CItab_edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CItab_edit_buttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CItab_edit_buttonActionPerformed

    private void CItab_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CItab_add_buttonActionPerformed
        // TODO add your handling code here:
        addDialogClearInputFields();
        addDialog.setVisible(true);
        addDialog.pack();
    }//GEN-LAST:event_CItab_add_buttonActionPerformed

    private void addDialogCreditLimitField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDialogCreditLimitField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addDialogCreditLimitField1ActionPerformed

    private void CItabEmailField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CItabEmailField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CItabEmailField1ActionPerformed

    private void addDialogFirstnameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDialogFirstnameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDialogFirstnameField1ActionPerformed

    private void addDialogDiscartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDialogDiscartButtonActionPerformed
        // TODO add your handling code here:
        addDialog.setVisible(false);
    }//GEN-LAST:event_addDialogDiscartButtonActionPerformed

    private void addDialogIDField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDialogIDField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDialogIDField1ActionPerformed

    private void addDialogAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDialogAcceptButtonActionPerformed
        // TODO add your handling code here:
        
        jTable1.getModel().insertRow(new Object[]{addDialogIDField1.getText(), "Column 2", "Column 3"});
    }//GEN-LAST:event_addDialogAcceptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CItabEmailField1;
    private javax.swing.JButton CItab_Push_button;
    private javax.swing.JButton CItab_add_button;
    private javax.swing.JButton CItab_delete_button;
    private javax.swing.JButton CItab_edit_button;
    private javax.swing.JButton CItab_fetch_button;
    private javax.swing.JTabbedPane Customer_info_tab;
    private javax.swing.JDialog addDialog;
    private javax.swing.JButton addDialogAcceptButton;
    private javax.swing.JLabel addDialogBalance;
    private javax.swing.JTextField addDialogBalanceField1;
    private javax.swing.JLabel addDialogCreditLimit;
    private javax.swing.JTextField addDialogCreditLimitField1;
    private javax.swing.JButton addDialogDiscartButton;
    private javax.swing.JLabel addDialogEmailLabel;
    private javax.swing.JTextField addDialogFirstnameField1;
    private javax.swing.JTextField addDialogIDField1;
    private javax.swing.JLabel addDialogIDLabel1;
    private javax.swing.JTextField addDialogLastnameField1;
    private javax.swing.JLabel addDialogLastnameLabel1;
    private javax.swing.JLabel addDialogNameLabel1;
    private javax.swing.JLabel addDialogObsLabel;
    private javax.swing.JTextField addDialogPhoneField1;
    private javax.swing.JLabel addDialogPhoneLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void addDialogClearInputFields() {
        addDialogIDField1.setText("");
        addDialogFirstnameField1.setText("");
        addDialogLastnameField1.setText("");
        addDialogEmailLabel.setText("");
        addDialogCreditLimitField1.setText("");
        addDialogBalanceField1.setText("");
        addDialogPhoneField1.setText("");
        
    }
}
