/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import command.Invoker;
import controller.DatabaseController;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.SQLException;
import model.ResultSetTableModel;

/**
 *
 * @author Sth0r
 */
public class GUI extends javax.swing.JFrame {

    private Invoker invoker;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    
    private void setInputFieldsEdibel()
    {
        CItabIDField.setEditable(true);
        CItabFirstnameField.setEditable(true);
        CItabLastnameField.setEditable(true);
        CItabEmailField.setEditable(true);
        CItabCreditLimitField.setEditable(true);
        CItabBalanceField.setEditable(true);
    }
    
    private void clearInputFields()
    {
        CItabIDField.setText("");
        CItabFirstnameField.setText("");
        CItabLastnameField.setText("");
        CItabEmailField.setText("");
        CItabCreditLimitField.setText("");
        CItabBalanceField.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Customer_info_tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        CItab_add_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CItabIDField = new javax.swing.JTextField();
        CItab_ID_label = new javax.swing.JLabel();
        CItab_name_label = new javax.swing.JLabel();
        CItabFirstnameField = new javax.swing.JTextField();
        CItabLastnameField = new javax.swing.JTextField();
        CItab_lastname_label = new javax.swing.JLabel();
        CItab_edit_button = new javax.swing.JButton();
        CItab_delete_button = new javax.swing.JButton();
        CItab_discard_button = new javax.swing.JButton();
        CItab_accept_button = new javax.swing.JButton();
        CItab_Push_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CItabEmailField = new javax.swing.JTextField();
        CItabCreditLimitField = new javax.swing.JTextField();
        CItabBalanceField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CItab_fetch_button = new javax.swing.JButton();
        CItabPhoneField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CItab_add_button.setText("Add");
        CItab_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CItab_add_buttonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First name", "Last name", "balance", "Credit limit", "Email", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        CItabIDField.setEditable(false);
        CItabIDField.setText("jTextField1");

        CItab_ID_label.setText("ID:");

        CItab_name_label.setText("First name:");

        CItabFirstnameField.setEditable(false);
        CItabFirstnameField.setText("jTextField2");

        CItabLastnameField.setEditable(false);
        CItabLastnameField.setText("jTextField3");

        CItab_lastname_label.setText("Last name:");

        CItab_edit_button.setText("Edit");
        CItab_edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CItab_edit_buttonActionPerformed(evt);
            }
        });

        CItab_delete_button.setText("Delete");
        CItab_delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CItab_delete_buttonActionPerformed(evt);
            }
        });

        CItab_discard_button.setText("Discard");

        CItab_accept_button.setText("Accept");
        CItab_accept_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CItab_accept_buttonActionPerformed(evt);
            }
        });

        CItab_Push_button.setText("Push");

        jLabel4.setText("Email:");

        jLabel5.setText("Credit limit:");

        jLabel6.setText("Balance:");

        CItabEmailField.setEditable(false);
        CItabEmailField.setText("jTextField4");
        CItabEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CItabEmailFieldActionPerformed(evt);
            }
        });

        CItabCreditLimitField.setEditable(false);
        CItabCreditLimitField.setText("jTextField5");
        CItabCreditLimitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CItabCreditLimitFieldActionPerformed(evt);
            }
        });

        CItabBalanceField.setEditable(false);
        CItabBalanceField.setText("jTextField6");

        jLabel7.setText("OBS eg \"-200\"");

        CItab_fetch_button.setText("Fetch");

        CItabPhoneField.setText("jTextField1");

        jLabel1.setText("Phone:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CItab_name_label)
                            .addComponent(CItab_ID_label)
                            .addComponent(CItab_lastname_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CItabLastnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(CItabIDField)
                            .addComponent(CItabFirstnameField))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CItabCreditLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CItabBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CItabEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CItabPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CItab_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CItab_edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CItab_delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CItab_fetch_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CItab_discard_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CItab_accept_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CItab_Push_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 391, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CItab_add_button)
                    .addComponent(CItab_edit_button)
                    .addComponent(CItab_delete_button)
                    .addComponent(CItab_fetch_button))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CItabIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CItab_ID_label)
                    .addComponent(jLabel4)
                    .addComponent(CItabEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CItabPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CItab_name_label)
                    .addComponent(CItabFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(CItabCreditLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CItabLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CItabBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CItab_lastname_label)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CItab_discard_button)
                    .addComponent(CItab_accept_button)
                    .addComponent(CItab_Push_button))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Customer_info_tab.addTab("Customer info", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        Customer_info_tab.addTab("Event log", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Customer_info_tab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Customer_info_tab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CItab_accept_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CItab_accept_buttonActionPerformed
        // TODO add your handling code here:
        try {
        jTable1.getModel().setValueAt(CItabIDField.getText(), jTable1.getSelectedRow(), 0);
        jTable1.getModel().setValueAt(CItabFirstnameField.getText(), jTable1.getSelectedRow(), 1);
        jTable1.getModel().setValueAt(CItabLastnameField.getText(), jTable1.getSelectedRow(), 2);
        jTable1.getModel().setValueAt(CItabBalanceField.getText(), jTable1.getSelectedRow(), 3);
        jTable1.getModel().setValueAt(CItabCreditLimitField.getText(), jTable1.getSelectedRow(), 4);
        jTable1.getModel().setValueAt(CItabEmailField.getText(), jTable1.getSelectedRow(), 5);
        jTable1.getModel().setValueAt(CItabPhoneField.getText(), jTable1.getSelectedRow(), 6);
        } catch (Exception e) {
            System.out.println("Der skete en fejl, i \"CItab_accept_buttonActionPerformed\"");
        }
    }//GEN-LAST:event_CItab_accept_buttonActionPerformed

    private void CItab_delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CItab_delete_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CItab_delete_buttonActionPerformed

    private void CItab_edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CItab_edit_buttonActionPerformed
        // TODO add your handling code here:
        setInputFieldsEdibel();
        
    }//GEN-LAST:event_CItab_edit_buttonActionPerformed

    private void CItab_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CItab_add_buttonActionPerformed
        // TODO add your handling code here:
        setInputFieldsEdibel();
        clearInputFields();
        
    }//GEN-LAST:event_CItab_add_buttonActionPerformed

    private void CItabEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CItabEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CItabEmailFieldActionPerformed

    private void CItabCreditLimitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CItabCreditLimitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CItabCreditLimitFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CItabBalanceField;
    private javax.swing.JTextField CItabCreditLimitField;
    private javax.swing.JTextField CItabEmailField;
    private javax.swing.JTextField CItabFirstnameField;
    private javax.swing.JTextField CItabIDField;
    private javax.swing.JTextField CItabLastnameField;
    private javax.swing.JTextField CItabPhoneField;
    private javax.swing.JLabel CItab_ID_label;
    private javax.swing.JButton CItab_Push_button;
    private javax.swing.JButton CItab_accept_button;
    private javax.swing.JButton CItab_add_button;
    private javax.swing.JButton CItab_delete_button;
    private javax.swing.JButton CItab_discard_button;
    private javax.swing.JButton CItab_edit_button;
    private javax.swing.JButton CItab_fetch_button;
    private javax.swing.JLabel CItab_lastname_label;
    private javax.swing.JLabel CItab_name_label;
    private javax.swing.JTabbedPane Customer_info_tab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
